
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.13
fail_fast: false
minimum_pre_commit_version: 4.1.0
repos:
    - repo: https://github.com/asottile/setup-cfg-fmt
      rev: v3.2.0
      hooks:
        - id: setup-cfg-fmt
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
        - id: debug-statements
    - repo: https://github.com/asottile/reorder-python-imports
      rev: v3.16.0
      hooks:
      - id: reorder-python-imports
        args: [--py310-plus]
    - repo: https://github.com/asottile/add-trailing-comma
      rev: v4.0.0
      hooks:
        - id: add-trailing-comma
    - repo: https://github.com/frnmst/md-toc
      rev: 9.0.0
      hooks:
          - id: md-toc
            args: [--in-place, github, --header-levels, '6']
            stages:
              - manual
    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.48.0
      hooks:
          - id: markdownlint
            args: [--fix]
            stages:
                - manual
    - repo: https://github.com/executablebooks/mdformat
      rev: 1.0.0
      hooks:
          - id: mdformat
            additional_dependencies:
                - mdformat-gfm
            stages:
                - manual
    - repo: https://github.com/lovesegfault/beautysh
      rev: v6.4.3
      hooks:
          - id: beautysh
            args: [--indent-size, '4']
    - repo: https://github.com/openstack/bashate
      rev: 2.1.1
      hooks:
          - id: bashate
            args: ['--ignore=E006,E020']
    - repo: https://github.com/jendrikseipp/vulture
      rev: v2.16
      hooks:
        - id: vulture
          args: ["pre_commit_hooks/"]
          stages:
              - manual
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.15.8
      hooks:
          - id: ruff
            args: [--config=config-tools/ruff.toml, --fix]
          - id: ruff-format
            args: [--config=config-tools/ruff.toml]
    - repo: https://github.com/pre-commit/mirrors-pylint
      rev: v3.0.0a5
      hooks:
          - id: pylint
            args: [--rcfile=setup.cfg, --reports=no, --persistent=no, --score=no, --disable=E0401]
            stages:
                - manual
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.19.1
      hooks:
          - id: mypy
            args: [--config-file=setup.cfg]
            stages:
                - manual
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.10.0
      hooks:
          - id: python-no-eval
          - id: python-no-log-warn
          - id: python-use-type-annotations
          - id: rst-backticks
    - repo: https://github.com/MarcoGorelli/auto-walrus
      rev: v0.2.2
      hooks:
          - id: auto-walrus
    - repo: https://github.com/dannysepler/rm_unneeded_f_str
      rev: v0.2.0
      hooks:
          - id: rm-unneeded-f-str
    - repo: https://github.com/PyCQA/bandit
      rev: 1.9.4
      hooks:
          - id: bandit
            args: [-c, config-tools/bandit.yaml]
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.21.2
      hooks:
          - id: pyupgrade
            args: [--py3-only, --py310-plus]
    - repo: https://github.com/chrysa/pre-commit-tools
      rev: '0.0.60'
      hooks:
          - id: python-print-detection
          - id: python-pprint-detection
          - id: debugger-detection
          - id: yaml-sorter
            additional_dependencies: [PyYAML]
          - id: json-sorter
          - id: requirements-sort
          - id: env-file-check
          - id: python-logger-detection
          - id: python-unreachable-code
          - id: python-dead-code
            stages: [manual]
    - repo: https://github.com/chrysa/pre-commit-hooks-changelog
      rev: 'v0.1.4'
      hooks:
          - id: generate-changelog
            stages: [manual]
