
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.13
fail_fast: false
minimum_pre_commit_version: 4.1.0
repos:
    - repo: https://github.com/asottile/setup-cfg-fmt
      rev: 583e6b807299b819eef8ec12f3ac4341dc0f2f15
      hooks:
        - id: setup-cfg-fmt
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
        - id: debug-statements
    - repo: https://github.com/asottile/setup-cfg-fmt
      rev: 583e6b807299b819eef8ec12f3ac4341dc0f2f15
      hooks:
        - id: setup-cfg-fmt
    - repo: https://github.com/asottile/reorder-python-imports
      rev: ce5979f64e3e0e48df463852cd9bc6c53df936e1
      hooks:
      - id: reorder-python-imports
        args: [--py310-plus]
    - repo: https://github.com/asottile/add-trailing-comma
      rev: e010ba1c8190323b9c68d4d398789dc867ecd0b2
      hooks:
        - id: add-trailing-comma
    - repo: https://github.com/frnmst/md-toc
      rev: 8.2.0
      hooks:
          - id: md-toc
            args: [--in-place, github, --header-levels, '6']
            stages:
              - manual
    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: febea6211c11cfb4c763a6f8abbd456148b7a029
      hooks:
          - id: markdownlint
            args: [--fix]
            stages:
                - manual
    - repo: https://github.com/executablebooks/mdformat
      rev: 782cb22f294bc4ce48368ee173de4837fc208ecf
      hooks:
          - id: mdformat
        # Optionally add plugins
            additional_dependencies:
                - mdformat-gfm
                - mdformat-black
            stages:
                - manual
    - repo: https://github.com/lovesegfault/beautysh.git
      rev: 9845efc3ea3e86cc0d41465d720a47f521b2799c
      hooks:
          - id: beautysh
            args: [--indent-size, '4']
    - repo: https://github.com/openstack/bashate.git
      rev: f5426a8c83b429b7bae80d9004bdebc73ebe8137
      hooks:
          - id: bashate
            args: ['--ignore=E006,E020']
    - repo: https://github.com/jendrikseipp/vulture
      rev: 'v2.3'
      hooks:
        - id: vulture
          args: ["pre_commit_hooks/"]
          stages:
              - manual
    - repo: https://github.com/psf/black
      rev: 738c2789cc07dbbd6bcf5908fd06627ee8d5cd6c
      hooks:
          - id: black
            args: [--config=config-tools/black.toml]
    - repo: https://github.com/asottile/blacken-docs
      rev: 96bc175074492573e3df847d9153a0689ed18ac2
      hooks:
          - id: blacken-docs
            additional_dependencies:
                - black
    - repo: https://github.com/pre-commit/mirrors-pylint
      rev: a1b176a5ee919967cf01e87c0222bd64b94fe0de
      hooks:
          - id: pylint
            args: [--rcfile=setup.cfg, --reports=no, --persistent=no, --score=no, --disable=E0401]
            stages:
                - manual
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.5.1
      hooks:
          - id: mypy
            args: [--config-file=setup.cfg]
            stages:
                - manual
    - repo: https://github.com/pycqa/flake8
      rev: faef3587480ab621dd2fd2d87ec36fc479749a90
      hooks:
          - id: flake8
            args: [--config=setup.cfg]
            stages:
                - manual
            additional_dependencies:
                - flake8-black
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: de3636cb98b3aadb86ab9570c0622ba17a078aeb
      hooks:
          - id: python-no-eval
          - id: python-no-log-warn
          - id: python-use-type-annotations
          - id: rst-backticks
    - repo: https://github.com/MarcoGorelli/auto-walrus
      rev: 3154eabcea87e810d7ae34046ba4132b697d79e3
      hooks:
          - id: auto-walrus
    - repo: https://github.com/dannysepler/rm_unneeded_f_str
      rev: df396a8bfdeced1a011c7d9d6787aa7f49ac8634
      hooks:
          - id: rm-unneeded-f-str
    - repo: https://github.com/PyCQA/bandit
      rev: 6969489ff711a1762bd44d00eaaba75f0c7102f6
      hooks:
          - id: bandit
            args: [-c, config-tools/bandit.yaml]
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.15.0
      hooks:
          - id: pyupgrade
            args: [--py3-only, --py310-plus]
