- id: format-dockerfiles
  additional_dependencies:
    - dockerfile-parse
  description: format dockerfiles
  entry: format-dockerfile
  files: Dockerfile, .[dD]ockerfile$
  language: python
  language_version: '3.10'
  minimum_pre_commit_version: '3.7.1'
  name: format dockerfiles
  types: ["dockerfile"]
- id: python-print-detection
  entry: print-detection
  files: .py$
  language: python
  language_version: '3.10'
  minimum_pre_commit_version: '3.7.1'
  name: detect print on python code
  types: ["python"]
- id: python-pprint-detection
  entry: pprint-detection
  files: .py$
  language: python
  language_version: '3.10'
  minimum_pre_commit_version: '3.7.1'
  name: detect pprint on python code
  types: ["python"]
- id: pylint-with-html-report
  additional_dependencies:
    - pylint
    - pylint-report
  description: genereate html report from pylint
  entry: pylint-report-html
  language: python
  minimum_pre_commit_version: '3.7.1'
  name: pylint html report
  language_version: '3.10'
  types: ["python"]
- id: yaml-sorter
  entry: yaml-sorter
  exclude: .pre-commit-config.yaml
  files: .yml$, .yaml$
  language: python
  language_version: '3.10'
  minimum_pre_commit_version: '3.7.1'
  name: sort yaml file alphabeticly for root and sub elements
  types: ["yaml"]
  additional_dependencies:
    - pyyaml
