- id: format-dockerfiles
  additional_dependencies:
    - dockerfile-parse
  description: format dockerfiles
  entry: format-dockerfile
  files: Dockerfile, .dockerfile$, .Dockerfile$
  language: python
  language_version: '3.10'
  minimum_pre_commit_version: '2.20.0'
  name: format dockerfiles
  types: ["dockerfile"]
- id: python-print-detection
  entry: print-detection
  files: .py$
  language: python
  language_version: '3.10'
  minimum_pre_commit_version: '2.20.0'
  name: detect print on python code
  types: ["python"]
- id: python-pprint-detection
  entry: pprint-detection
  files: .py$
  language: python
  language_version: '3.10'
  minimum_pre_commit_version: '2.20.0'
  name: detect pprint on python code
  types: ["python"]
- id: pylint-with-html-report
  additional_dependencies:
    - pylint
    - pylint-report
  description: genereate html report from pylint
  entry: pylint-report-html
  language: python
  minimum_pre_commit_version: '2.20.0'
  name: pylint html report
  language_version: '3.10'
  types: ["python"]
