sonar.projectKey=chrysa_pre-commit-tools
sonar.organization=chrysa
sonar.projectName=pre-commit-tools
sonar.sources=pre_commit_hooks
sonar.tests=tests
sonar.python.version=3.14
sonar.python.coverage.reportPaths=reports/coverage.xml
sonar.python.ruff.reportPaths=reports/ruff.json
sonar.python.mypy.reportPaths=reports/mypy.txt
sonar.python.xunit.reportPath=reports/junit.xml
sonar.exclusions=**/__pycache__/**,**/*.egg-info/**,**/.git/**
