sonar.projectKey=chrysa_pre-commit-tools
sonar.organization=chrysa
sonar.projectName=pre-commit-tools
sonar.sources=pre_commit_hooks
sonar.tests=tests
sonar.python.version=3.14
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/.mypy_cache/**
sonar.coverage.exclusions=tests/**,pre_commit_hooks/pylint_report_html.py,pre_commit_hooks/tools/update_readme.py
