updates:
- directory: /
  groups:
    docker:
      patterns:
      - dockerfile-parse*
    linting:
      patterns:
      - ruff*
      - mypy*
    security:
      patterns:
      - detect-secrets*
      - bandit*
      - pip-audit*
    testing:
      patterns:
      - pytest*
      - coverage*
      - pytest-cov*
    tree-sitter:
      patterns:
      - tree-sitter*
    yaml:
      patterns:
      - PyYAML*
  labels:
  - dependencies
  - python
  open-pull-requests-limit: 5
  package-ecosystem: pip
  schedule:
    day: monday
    interval: weekly
- directory: /
  groups:
    actions-core:
      patterns:
      - actions/*
    codecov:
      patterns:
      - codecov/*
    gittools:
      patterns:
      - gittools/*
    reporting:
      patterns:
      - EnricoMi/*
    sonar:
      patterns:
      - SonarSource/*
  labels:
  - dependencies
  - github-actions
  open-pull-requests-limit: 5
  package-ecosystem: github-actions
  schedule:
    day: monday
    interval: weekly
- directory: /
  labels:
  - dependencies
  - pre-commit
  open-pull-requests-limit: 5
  package-ecosystem: pre-commit
  schedule:
    day: monday
    interval: weekly
version: 2
