---
name: Actionlint

on:
    pull_request:
        paths:
            - .github/actionlint.yaml
            - .github/workflows/**
    push:
        branches: [main, master, develop]
        paths:
            - .github/workflows/**

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    call:
        uses: chrysa/github-actions/.github/workflows/action-check.yml@v1.6.0
