---
name: Auto Assign Reviewers

on:
    pull_request:
        types: [opened, ready_for_review, reopened]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    call:
        uses: chrysa/github-actions/.github/workflows/auto-assign.yml@v1.6.0
