---
name: PR Labeler

on:
    pull_request_target:
        types: [opened, reopened, synchronize]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    call:
        uses: chrysa/github-actions/.github/workflows/labeler.yml@v1.6.0
