---
name: pre-commit

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    pre-commit:
        name: Run pre-commit hooks
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-python@v6
              with:
                  python-version: '3.14'  # keep in sync with config job in ci.yml
            - uses: pre-commit/action@v3.0.1
