---
name: pre-commit

on:
    pull_request:
        branches: [main, develop]
    push:
        branches: [main, develop, "feat/**", "feature/**", "fix/**"]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    call:
        name: Run pre-commit hooks
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - uses: actions/checkout@v7.0.1
            - uses: actions/setup-python@v7.0.0
              with:
                  python-version: "3.14"
            - name: Install package for system hooks
              run: pip install -e '.[yaml,format_dockerfile,ts_unreachable_code]'
            - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
              env:
                  SKIP: no-commit-to-branch
