---
name: Label Pull Request Size

on:
    pull_request_target:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    call:
        uses: chrysa/github-actions/.github/workflows/pull-request-size.yml@v1.6.0
